# Nav2 Configuration for Bipedal Humanoid Navigation

# This configuration adapts Nav2 for bipedal humanoid movement
# with considerations for balance and stability

amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_delay: 0.2
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: "map"
    robot_frame: "base_link"
    odom_topic: "odom"
    bt_loop_duration: 10
    default_server_timeout: 20
    # Bipedal-specific navigation behavior tree
    # Takes into account balance constraints for humanoid movement
    default_nav_through_poses_bt_xml: "package://nav2_bipedal_configs/bt/bipedal_navigate_through_poses_w_replanning_and_recovery.xml"
    default_nav_to_pose_bt_xml: "package://nav2_bipedal_configs/bt/bipedal_navigate_to_pose_w_replanning_and_recovery.xml"
    # Specific node configurations
    NavigateThroughPoses.xmll: "package://nav2_bt_navigator/bt_xml_v0.4/navigate_through_poses.xml"
    NavigateToPose.xml: "package://nav2_bt_navigator/bt_xml_v0.4/navigate_to_pose.xml"

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    # Bipedal-specific controller configuration
    # Adjusted for stable humanoid locomotion
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    # DWB Controller
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_horizon: 1.0
      dt: 0.1
      batch_size: 1000
      vx_samples: 20
      vy_samples: 5
      omega_samples: 20
      model_frequency: 30.0
      # Bipedal-specific constraints
      acceleration_limits_xy: 2.0  # Lower for stability
      acceleration_limits_theta: 3.0
      deceleration_limits_xy: 2.0
      deceleration_limits_theta: 3.0
      
      # Robot geometry for bipedal walking
      robot_radius: 0.3  # Approximate humanoid foot base
      obstacles_topic: "/costmap/voxel_grid"
      goal_tolerance: 1.0  # Slightly larger for bipedal stability
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      transform_tolerance: 0.1
      velocity_scaling_window: 10
      frequency: 20.0

local_costmap:
  ros__parameters:
    use_sim_time: True
    update_frequency: 10.0
    publish_frequency: 10.0
    global_frame: "odom"
    robot_base_frame: "base_link"
    use_rollout_costs: true
    always_send_full_costmap: true
    # Bipedal-specific local costmap
    # Adjusted for humanoid footprint and balance
    width: 10
    height: 10
    resolution: 0.05  # Higher resolution for precise footstep planning
    origin_x: -5.0
    origin_y: -5.0
    # Footprint slightly larger for bipedal stability
    footprint: "[[-0.3, -0.2], [-0.3, 0.2], [0.4, 0.2], [0.4, -0.2]]"
    plugins: ["voxel_layer", "inflation_layer"]
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.55
    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      enabled: True
      voxel_size: 0.05
      # Bipedal-specific obstacle handling for stable path planning
      max_obstacle_height: 2.0
      mark_threshold: 0
      observation_sources: "scan"
      scan:
        topic: "/laser_scan"
        max_obstacle_height: 2.0
        clearing: True
        marking: True
        data_type: "LaserScan"
        raytrace_max_range: 10.0
        raytrace_min_range: 0.0
        obstacle_max_range: 10.0
        obstacle_min_range: 0.0

global_costmap:
  ros__parameters:
    use_sim_time: True
    update_frequency: 1.0
    publish_frequency: 1.0
    global_frame: "map"
    robot_base_frame: "base_link"
    # Bipedal-specific global costmap
    width: 200
    height: 200
    resolution: 0.05
    origin_x: -100.0
    origin_y: -100.0
    # Larger footprint for bipedal navigation and stability
    footprint: "[[-0.3, -0.2], [-0.3, 0.2], [0.4, 0.2], [0.4, -0.2]]"
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: True
      observation_sources: "scan"
      scan:
        topic: "/laser_scan"
        max_obstacle_height: 2.0
        clearing: True
        marking: True
        data_type: "LaserScan"
        raytrace_max_range: 10.0
        raytrace_min_range: 0.0
        obstacle_max_range: 10.0
        obstacle_min_range: 0.0
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: True
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.55

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    # Bipedal-specific path planner configuration
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5  # Slightly higher tolerance for bipedal movement
      use_astar: false
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: True
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: "local_costmap/costmap_raw"
    footprint_topic: "local_costmap/published_footprint"
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
      # Bipedal-specific spin behavior parameters
      # Slower and more controlled than wheeled robot
      spin_dist: 1.57  # 90 degrees for bipedal turn
      time_allowance: 100.0
    backup:
      plugin: "nav2_behaviors::BackUp"
      # Bipedal-specific backup behavior
      # Shorter distances and slower speeds for stability
      backup_dist: 0.15
      backup_speed: 0.025
      time_allowance: 10.0
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
      # Bipedal-specific drive behavior
      drive_on_heading_max_approach_dist: 0.3
      drive_on_heading_range_from_goal: 0.2
      drive_on_heading_angle_tolerance: 0.25
      time_allowance: 10.0
    wait:
      plugin: "nav2_behaviors::Wait"
      time_allowance: 1000.0